const sonnyAngels = [
  {
    name: "Peanut",
    type: "secret",
    points: 200,
    image: "images/peanut.png",
    alt: "Secret Peanut Sonny Angel",
  },
  {
    name: "Turtle",
    type: "secret",
    points: 150,
    image: "images/turtle.png",
    alt: "Secret Turtle Sonny Angel",
  },
  {
    name: "Sprout",
    type: "secret",
    points: 200,
    image: "images/sprout.png",
    alt: "Secret Sprout Sonny Angel",
  },
  {
    name: "GOL Chocolate",
    type: "limited",
    points: 22,
    image: "images/GOL_chocolate.png",
    alt: "Limited Gifts of Love Chocolate Sonny Angel",
  },
  {
    name: "Cat Life Siamese",
    type: "limited",
    points: 32,
    image: "images/cat_life_siamese.png",
    alt: "Limited Cat Life Siamese Sonny Angel",
  },
  {
    name: "Jeju Rabbit",
    type: "limited",
    points: 37,
    image: "images/jeju_rabbit.png",
    alt: "Limited Jeju Rabbit Sonny Angel",
  },
  {
    name: "Lime Dog",
    type: "limited",
    points: 42,
    image: "images/lime_dog.png",
    alt: "Limited Lime Dog Sonny Angel",
  },
  {
    name: "Seoul Strawberry",
    type: "limited",
    points: 45,
    image: "images/seoul_strawberry.png",
    alt: "Limited Seoul Strawberry Sonny Angel",
  },
  {
    name: "Easy Moment",
    type: "limited",
    points: 95,
    image: "images/easy_moment.png",
    alt: "Limited Enjoy the Moment Easy Moment Sonny Angel",
  },
  {
    name: "Carrot",
    type: "regular",
    points: 10,
    image: "images/carrot.png",
    alt: "Regular Carrot Sonny Angel",
  },
  {
    name: "Carnation",
    type: "regular",
    points: 10,
    image: "images/carnation.png",
    alt: "Regular Carnation Sonny Angel",
  },
  {
    name: "Tiger",
    type: "regular",
    points: 11,
    image: "images/tiger.png",
    alt: "Regular Tiger Sonny Angel",
  },
  {
    name: "Dragonfruit",
    type: "regular",
    points: 12,
    image: "images/dragonfruit.png",
    alt: "Regular Dragonfruit Sonny Angel",
  },
  {
    name: "Giraffe",
    type: "regular",
    points: 13,
    image: "images/giraffe.png",
    alt: "Regular Giraffe Sonny Angel",
  },
  {
    name: "Sheep",
    type: "regular",
    points: 14,
    image: "images/sheep.png",
    alt: "Regular Sheep Sonny Angel",
  },
  {
    name: "Fawn",
    type: "regular",
    points: 14,
    image: "images/fawn.png",
    alt: "Regular Fawn Sonny Angel",
  },
  {
    name: "Tomato",
    type: "regular",
    points: 16,
    image: "images/tomato.png",
    alt: "Regular Tomato Sonny Angel",
  },
  {
    name: "Poodle",
    type: "regular",
    points: 17,
    image: "images/poodle.png",
    alt: "Regular Poodle Sonny Angel",
  },
  {
    name: "Poppy",
    type: "regular",
    points: 17,
    image: "images/poppy.png",
    alt: "Regular Poppy Sonny Angel",
  },
  {
    name: "Dalmatian",
    type: "regular",
    points: 18,
    image: "images/dalmatian.png",
    alt: "Regular Dalmatian Sonny Angel",
  },
  {
    name: "Monkey",
    type: "regular",
    points: 18,
    image:
      "images/monkey.png",
    alt: "Regular Monkey Sonny Angel",
  },
  {
    name: "Calico",
    type: "regular",
    points: 18,
    image: "images/calico.png",
    alt: "Regular Calico Sonny Angel",
  },
  {
    name: "Frog",
    type: "regular",
    points: 20,
    image: "images/frog.png",
    alt: "Regular Frog Sonny Angel",
  },
  {
    name: "Pudding",
    type: "regular",
    points: 20,
    image:
      "images/pudding.png",
    alt: "Regular Pudding Sonny Angel",
  },
  {
    name: "Strawberry Shortcake",
    type: "regular",
    points: 23,
    image:
      "images/strawberry_shortcake.png",
    alt: "Regular Strawberry Shortcake Sonny Angel",
  },
  {
    name: "Cow",
    type: "regular",
    points: 25,
    image:
      "images/cow.png",
    alt: "Regular Cow Sonny Angel",
  },
  {
    name: "Lilly Bell",
    type: "regular",
    points: 25,
    image: "images/lilly_bell.png",
    alt: "Regular Lilly Bell Sonny Angel",
  },
  {
    name: "Rabbit",
    type: "regular",
    points: 30,
    image:
      "images/rabbit.png",
    alt: "Regular Rabbit Sonny Angel",
  },
  {
    name: "Strawberry",
    type: "regular",
    points: 35,
    image:
      "images/strawberry.png",
    alt: "Regular Strawberry Sonny Angel",
  },
  {
    name: "Lop Ear",
    type: "regular",
    points: 40,
    image:
      "images/lop_ear.png",
    alt: "Regular Lop Ear Rabbit Sonny Angel",
  },
];
